-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 12:28:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fa_training_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fa_training_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fa_training_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fa_training_system` ;

-- -----------------------------------------------------
-- Table `fa_training_system`.`assessments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`assessments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `assignment` FLOAT NULL DEFAULT NULL,
  `final` FLOAT NULL DEFAULT NULL,
  `final_practice` FLOAT NULL DEFAULT NULL,
  `final_theory` FLOAT NULL DEFAULT NULL,
  `gpa` FLOAT NULL DEFAULT NULL,
  `quiz` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`attendees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`attendees` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_75u38dvm5ht4p4tudfqbb1prh` (`type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`levels` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_e1ejnmsswocdocld1t1iwsvr5` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `permissions` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ofx66keruapi6vyqpv6f2or37` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `activated` BIT(1) NOT NULL,
  `avatar_url` VARCHAR(255) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `gender` BIT(1) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `level_id` BIGINT NULL DEFAULT NULL,
  `role_id` BIGINT NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  INDEX `FKhjemv8nqu3o0rutwrhlgca5in` (`level_id` ASC) VISIBLE,
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKhjemv8nqu3o0rutwrhlgca5in`
    FOREIGN KEY (`level_id`)
    REFERENCES `fa_training_system`.`levels` (`id`),
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `fa_training_system`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`programs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_at` DATETIME(6) NULL DEFAULT NULL,
  `activated` BIT(1) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `last_modified_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_4uh20rvftatfys82a9nkvpl0o` (`name` ASC) VISIBLE,
  INDEX `FKlrp6u3c081ppocuppb676c7gy` (`created_by` ASC) VISIBLE,
  INDEX `FK4cyb4heqhy4xgoy2pfuuwjqdq` (`last_modified_by` ASC) VISIBLE,
  CONSTRAINT `FK4cyb4heqhy4xgoy2pfuuwjqdq`
    FOREIGN KEY (`last_modified_by`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKlrp6u3c081ppocuppb676c7gy`
    FOREIGN KEY (`created_by`)
    REFERENCES `fa_training_system`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`classes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_at` DATETIME(6) NULL DEFAULT NULL,
  `code` VARCHAR(50) NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `last_modified_by` BIGINT NULL DEFAULT NULL,
  `program_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ivcaxrbwnp0dosg2gj4i3sxpq` (`code` ASC) VISIBLE,
  INDEX `FKbiegjf3djr7vcre1jxun3lbhh` (`created_by` ASC) VISIBLE,
  INDEX `FKd9jxhyf732e1o7ayctf7yuugp` (`last_modified_by` ASC) VISIBLE,
  INDEX `FKthmk4awc7ft3lg8ud2behicfs` (`program_id` ASC) VISIBLE,
  CONSTRAINT `FKbiegjf3djr7vcre1jxun3lbhh`
    FOREIGN KEY (`created_by`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKd9jxhyf732e1o7ayctf7yuugp`
    FOREIGN KEY (`last_modified_by`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKthmk4awc7ft3lg8ud2behicfs`
    FOREIGN KEY (`program_id`)
    REFERENCES `fa_training_system`.`programs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`locations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `fsu` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`class_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`class_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `accepted` INT NULL DEFAULT NULL,
  `actual` INT NULL DEFAULT NULL,
  `finish_at` TIME NULL DEFAULT NULL,
  `others` VARCHAR(200) NULL DEFAULT NULL,
  `planned` INT NULL DEFAULT NULL,
  `start_at` TIME NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  `attendee_id` BIGINT NULL DEFAULT NULL,
  `class_id` BIGINT NOT NULL,
  `location_id` BIGINT NULL DEFAULT NULL,
  `contact_point` VARCHAR(255) NULL DEFAULT NULL,
  `detail_location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrox1p5mwmlawehs4sqae6f2cu` (`attendee_id` ASC) VISIBLE,
  INDEX `FKjuc5vv7suu2rg9fe9j14nl5vp` (`class_id` ASC) VISIBLE,
  INDEX `FKqa7bkgps47qjh7cxwsa9gqwks` (`location_id` ASC) VISIBLE,
  CONSTRAINT `FKjuc5vv7suu2rg9fe9j14nl5vp`
    FOREIGN KEY (`class_id`)
    REFERENCES `fa_training_system`.`classes` (`id`),
  CONSTRAINT `FKqa7bkgps47qjh7cxwsa9gqwks`
    FOREIGN KEY (`location_id`)
    REFERENCES `fa_training_system`.`locations` (`id`),
  CONSTRAINT `FKrox1p5mwmlawehs4sqae6f2cu`
    FOREIGN KEY (`attendee_id`)
    REFERENCES `fa_training_system`.`attendees` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`training_principle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`training_principle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `marking` TEXT NULL DEFAULT NULL,
  `others` TEXT NULL DEFAULT NULL,
  `re_test` TEXT NULL DEFAULT NULL,
  `training` TEXT NULL DEFAULT NULL,
  `waiver_criteria` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`syllabuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`syllabuses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_at` DATETIME(6) NULL DEFAULT NULL,
  `attendee_number` INT NULL DEFAULT NULL,
  `code` VARCHAR(20) NOT NULL,
  `course_objective` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `technical_requirement` TEXT NULL DEFAULT NULL,
  `training_principle` TEXT NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `last_modified_by` BIGINT NULL DEFAULT NULL,
  `level_id` BIGINT NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `version` FLOAT NULL DEFAULT NULL,
  `assessment_id` BIGINT NULL DEFAULT NULL,
  `training_principle_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_e7s6kp3i6cm5rbr4teubcgey4` (`code` ASC) VISIBLE,
  INDEX `FK1ysb28n6acuj6ka2qbk7jfxl9` (`created_by` ASC) VISIBLE,
  INDEX `FKavtmf636td29vit0r4hufwr0a` (`last_modified_by` ASC) VISIBLE,
  INDEX `FKtlybknyldvpkfyk329rgo8hlw` (`level_id` ASC) VISIBLE,
  INDEX `FKog7ydovun9by8gil6ohde5x1t` (`assessment_id` ASC) VISIBLE,
  INDEX `FK16ekmmrw5ng1rbw8310ix75pt` (`training_principle_id` ASC) VISIBLE,
  CONSTRAINT `FK16ekmmrw5ng1rbw8310ix75pt`
    FOREIGN KEY (`training_principle_id`)
    REFERENCES `fa_training_system`.`training_principle` (`id`),
  CONSTRAINT `FK1ysb28n6acuj6ka2qbk7jfxl9`
    FOREIGN KEY (`created_by`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKavtmf636td29vit0r4hufwr0a`
    FOREIGN KEY (`last_modified_by`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKog7ydovun9by8gil6ohde5x1t`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `fa_training_system`.`assessments` (`id`),
  CONSTRAINT `FKtlybknyldvpkfyk329rgo8hlw`
    FOREIGN KEY (`level_id`)
    REFERENCES `fa_training_system`.`levels` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`sessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `index` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `syllabus_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh0x2ptmxtqkfbjhbkoevwkts7` (`syllabus_id` ASC) VISIBLE,
  CONSTRAINT `FKh0x2ptmxtqkfbjhbkoevwkts7`
    FOREIGN KEY (`syllabus_id`)
    REFERENCES `fa_training_system`.`syllabuses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`class_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`class_schedules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `study_date` DATE NULL DEFAULT NULL,
  `class_detail_id` BIGINT NULL DEFAULT NULL,
  `trainer_id` BIGINT NULL DEFAULT NULL,
  `session_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK3hr653l17gogn08c6or9junst` (`class_detail_id` ASC) VISIBLE,
  INDEX `FKfgq5lye3c64by4udqajlr279g` (`trainer_id` ASC) VISIBLE,
  INDEX `FK5upcw2hwhgv5gbkggmk42r7wc` (`session_id` ASC) VISIBLE,
  CONSTRAINT `FK3hr653l17gogn08c6or9junst`
    FOREIGN KEY (`class_detail_id`)
    REFERENCES `fa_training_system`.`class_details` (`id`),
  CONSTRAINT `FK5upcw2hwhgv5gbkggmk42r7wc`
    FOREIGN KEY (`session_id`)
    REFERENCES `fa_training_system`.`sessions` (`id`),
  CONSTRAINT `FKfgq5lye3c64by4udqajlr279g`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `fa_training_system`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`deliveries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_23btti2t7198im5s1enq84xwh` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`file_storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`file_storage` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`format_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`format_types` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ry7mnncrfp0a7d2q590u6hx0t` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`output_standards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`output_standards` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_3y4rci6j3m36u8wvs5fc35txy` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`units` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `index` INT NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `session_id` BIGINT NULL DEFAULT NULL,
  `total_duration_lesson` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKggkr7eghfph2og9yk21721di8` (`session_id` ASC) VISIBLE,
  CONSTRAINT `FKggkr7eghfph2og9yk21721di8`
    FOREIGN KEY (`session_id`)
    REFERENCES `fa_training_system`.`sessions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`lessons` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `duration` INT NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `delivery_id` BIGINT NULL DEFAULT NULL,
  `format_type_id` BIGINT NULL DEFAULT NULL,
  `output_standard_id` BIGINT NULL DEFAULT NULL,
  `unit_id` BIGINT NULL DEFAULT NULL,
  `index` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK18qao7xmeh7a8e1i0s3q3ik0e` (`delivery_id` ASC) VISIBLE,
  INDEX `FKemvrikd529cwhlk515kim2gve` (`format_type_id` ASC) VISIBLE,
  INDEX `FK8r17xqds2ig0mlk9jm0e53wcm` (`output_standard_id` ASC) VISIBLE,
  INDEX `FKfsvqlgk1jdfcd1h8biuwy55rn` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `FK18qao7xmeh7a8e1i0s3q3ik0e`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `fa_training_system`.`deliveries` (`id`),
  CONSTRAINT `FK8r17xqds2ig0mlk9jm0e53wcm`
    FOREIGN KEY (`output_standard_id`)
    REFERENCES `fa_training_system`.`output_standards` (`id`),
  CONSTRAINT `FKemvrikd529cwhlk515kim2gve`
    FOREIGN KEY (`format_type_id`)
    REFERENCES `fa_training_system`.`format_types` (`id`),
  CONSTRAINT `FKfsvqlgk1jdfcd1h8biuwy55rn`
    FOREIGN KEY (`unit_id`)
    REFERENCES `fa_training_system`.`units` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`materials` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `file_url` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `lesson_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKj3unvdjwlsccmqod6jl4w0vcp` (`created_by` ASC) VISIBLE,
  INDEX `FK24ruqpibfurlhb345nmqh08n` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `FK24ruqpibfurlhb345nmqh08n`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `fa_training_system`.`lessons` (`id`),
  CONSTRAINT `FKj3unvdjwlsccmqod6jl4w0vcp`
    FOREIGN KEY (`created_by`)
    REFERENCES `fa_training_system`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`program_syllabus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`program_syllabus` (
  `program_id` BIGINT NOT NULL,
  `syllabus_id` BIGINT NOT NULL,
  `syllabus_index` INT NOT NULL,
  PRIMARY KEY (`program_id`, `syllabus_index`),
  INDEX `FK8ks7nksqr16bpi4niyc86j8ap` (`syllabus_id` ASC) VISIBLE,
  CONSTRAINT `FK8ks7nksqr16bpi4niyc86j8ap`
    FOREIGN KEY (`syllabus_id`)
    REFERENCES `fa_training_system`.`syllabuses` (`id`),
  CONSTRAINT `FKdfxu0lcxgkxe849mafs4i6v9m`
    FOREIGN KEY (`program_id`)
    REFERENCES `fa_training_system`.`programs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fa_training_system`.`user_class_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fa_training_system`.`user_class_detail` (
  `class_detail_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  INDEX `FKjhfajenjj6qnbiugckn0j7kak` (`user_id` ASC) VISIBLE,
  INDEX `FKq6rrotmrcevydf36copjv6ppb` (`class_detail_id` ASC) VISIBLE,
  CONSTRAINT `FKjhfajenjj6qnbiugckn0j7kak`
    FOREIGN KEY (`user_id`)
    REFERENCES `fa_training_system`.`users` (`id`),
  CONSTRAINT `FKq6rrotmrcevydf36copjv6ppb`
    FOREIGN KEY (`class_detail_id`)
    REFERENCES `fa_training_system`.`class_details` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
